#!/usr/bin/env python3
import json
import codecs
import os
import filecmp
from collections import Counter

VERBOSE = False
# For every digest-based group, generate merged JSON metadata:
#	Tags: are joined without duplications, as a sorted list.
#	Description: do they match? If there is a single one, use that one
#	AltDescriptions: In case there is more than one not-matching description
#   Title: Use from the JSON or the alternative filenames.
#.  AltTitles: In case there is more than one not-matching title

{%- for i, group in digest_groups %}
tags = set()
descriptions = []
altdescriptions = []
titles = []
alttitles = []
paths = []
has_jsons = []
{% set ns = namespace(main_file='', main_file_path='') -%}
{% for j, e in group.iterrows() -%}
{% if e['has_json'] -%}
with codecs.open( "{{ e['fullpath'] }}.json", 'r','utf-8-sig') as f:
	js = json.load(f)
	tags.update( js['Tags'] if isinstance(js['Tags'], list)
		 else js['Tags'].split(' ') )
	descriptions.append(js['Description'])
	if 'AltDescriptions' in js: altdescriptions.extend(js['AltDescriptions'])
	titles.append(js['Title'])
	if 'AltTitles' in js: alttitles.extend(js['AltTitles'])
	{% if e['persist_version'] != KEPT_MARK -%}
	paths.append("{{ e['fullpath'] }}")
	has_jsons.append(True)
	{% else -%}
	{% set ns.main_file = e['name'] -%}
	{% set ns.main_file_path = e['fullpath'] -%}
	{% endif %}
{% else -%}
{% if e['persist_version'] != KEPT_MARK -%}
titles.append("{{ e['name'] }}")
paths.append("{{ e['fullpath'] }}")
has_jsons.append(False)
{% else -%}
{% set ns.main_file = e['name'] -%}
{% set ns.main_file_path = e['fullpath'] -%}
{% endif -%}
{% endif -%}
{% endfor -%}

metadata = {'Tags': sorted(list(tags)),
			'Description': '',
			'Title': '' }

descriptions = Counter(descriptions)
del descriptions['']
if (len(descriptions) >= 1):
	metadata['Description'] = descriptions.most_common(1)[0][0]

metadata['AltDescriptions'] = sorted(set(altdescriptions + [d[0] for d in descriptions.most_common()[1:]]))
if len(metadata['AltDescriptions']) == 0:
	del metadata['AltDescriptions']

titles = Counter(titles)
del titles['']
if len(titles) >= 1:
	metadata['Title'] = titles.most_common(1)[0][0]

metadata['AltTitles'] = sorted(set(alttitles + [t[0] for t in titles.most_common()[1:]]))
if len(metadata['AltTitles']) == 0:
	del metadata['AltTitles']

if ( ( len(metadata['Tags']) > 0 or metadata['Description'] != '' or metadata['Title'] != '' ) and
	 ( ('AltTitles' not in metadata or len(metadata['AltTitles']) > 0) and
	   ('AltDescriptions' not in metadata or len(metadata['AltDescriptions']) > 0) ) ):
	if VERBOSE: print("MERGED '{{ ns.main_file }}' = ", metadata)
	with open( "{{ ns.main_file_path }}.json", 'w') as f:
		json.dump(metadata, f)

for p,h in zip(paths, has_jsons):
	if filecmp.cmp('{{ ns.main_file_path }}', p, shallow=False):
		print("rm \"{}\"".format(p))
		os.remove("{}".format(p))
		if h:
			print("rm \"{}.json\"".format(p))
			os.remove("{}.json".format(p))

{% endfor %}

if VERBOSE: print('{{digest_groups|length}} digests processed')
{#print("{} / {} = {} files in total".format(count, count_nj, count_t))#}